version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: mysql://root:root@12345@db:3306/lottiefiles
      BASE_URL: http://localhost:4000
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:4000,http://localhost:5173,http://localhost:4173
      SERVER_PORT: 4000
    volumes:
      - ./backend/uploads:/app/uploads  # Mount the uploads directory
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      REACT_APP_GRAPHQL_API_URL: http://localhost:4000/graphql
    depends_on:
      - backend

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root@12345
      MYSQL_DATABASE: lottiefiles
      MYSQL_USER: root
      MYSQL_PASSWORD: root@12345
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
