services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root@12345
      - MYSQL_DATABASE=lottiefiles
      - MYSQL_USER=lottieuser
      - MYSQL_PASSWORD=lottiepassword
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DATABASE_URL: mysql://lottieuser:lottiepassword@db:3306/lottiefiles
    ports:
      - "4000:4000"
    environment:
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:4000,http://localhost:5173,http://localhost:4173,https://studio.apollographql.com
      DATABASE_URL: mysql://lottieuser:lottiepassword@db:3306/lottiefiles
      SERVER_PORT: 4000
      BASE_URL: http://localhost:4000
      WAIT_HOSTS: db:3306

    volumes:
      - ./backend/uploads:/app/uploads  # Mount the uploads directory
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:4173"
    depends_on:
      - backend

volumes:
  db_data:
